# Generated by Django 2.2.6 on 2019-10-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('absence_number', models.IntegerField()),
            ],
        ),
    ]
